"""Render the JUnit XML files in reports/tests/ as a Markdown table.

    pytest --junitxml=reports/tests/pytest_offline_and_model.xml
    pytest -m network --junitxml=reports/tests/pytest_network.xml
    python scripts/test_table.py            # -> reports/tests/results.md

docs/TEST_REPORT.md links to the output, so the list of passed tests is never typed by hand.
"""

from __future__ import annotations

import sys
import xml.etree.ElementTree as ET
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from contextlens.config import PATHS


def main() -> int:
    rows, totals = [], Counter()
    for xml in sorted((PATHS.reports / "tests").glob("*.xml")):
        for case in ET.parse(xml).getroot().iter("testcase"):  # noqa: S314
            if case.find("skipped") is not None:
                outcome = "SKIPPED"
            elif case.find("failure") is not None or case.find("error") is not None:
                outcome = "FAIL"
            else:
                outcome = "PASS"
            totals[outcome] += 1
            name = f"{case.get('classname', '').removeprefix('tests.')}::{case.get('name')}"
            rows.append(f"| {xml.stem} | `{name}` | {outcome} | {float(case.get('time', 0)):.2f} |")
    out = PATHS.reports / "tests" / "results.md"
    header = [
        "# Test results (generated by scripts/test_table.py from the JUnit XML files)",
        "",
        "Totals: " + ", ".join(f"{k} {v}" for k, v in sorted(totals.items())),
        "",
        "| run | test | outcome | seconds |",
        "|---|---|---|---:|",
    ]
    out.write_text("\n".join(header + rows) + "\n", encoding="utf-8")
    print(f"wrote {out}: {dict(totals)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
